
seleniumGrid=true
gridURL=http://192.168.1.132:4454

# Application-url
#url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
url=http://192.168.174.1/orangehrm/orangehrm-5.8/web/index.php/auth/login
url_grid=http://192.168.1.132/orangehrm/orangehrm-5.8/web/index.php/auth/login

#BrowserConfig
#browser=chrome
browser=edge

#credentials
username=mahesh
password=Mahesh@123

#implicit wait
implicitWait=10

#explicit wait
explicitWait=30